# ansible-playbook -i localhost, playbook.yml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    fqdn: foo.bar.example.com
    fqdn_last: "{{ fqdn.split('.')[-1] }}"
    fqdn_second_last: "{{ fqdn.split('.')[-2] }}"
      
  tasks:
    - name: Print variable
      ansible.builtin.debug:
        var: fqdn_last

    - name: Print variable
      ansible.builtin.debug:
        var: fqdn_second_last

    - name: Print variables combined
      ansible.builtin.debug:
        msg: "{{ fqdn_second_last + '.' + fqdn_last }}"
