# ansible-playbook -i localhost, playbook.yml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
    - name: Gather OS distribution facts
      ansible.builtin.setup:
        filter: "!all,!min,distribution,distribution_version"

    - name: Print OS distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Print facts
      ansible.builtin.debug:
        var: ansible_facts
