# ansible-playbook -i localhost, playbook.yml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    backup_mount_path: "/home"
    backup_protocol: "ext4"
    
  tasks:
    - name: Print ansible_facts
      debug:
        var: ansible_facts

    - name: Extract mount types
      ansible.builtin.set_fact:
        mount_types: "{{ ansible_facts.mounts | items2dict(key_name='mount', value_name='fstype') }}"

    - name: Check if mount type has changed
      ansible.builtin.set_fact:
        mount_type_changed: "{{ mount_types[backup_mount_path] | default('') != backup_protocol }}"

    - name: Print mount types
      debug:
        var: mount_types

    - name: Print mount type changed
      debug:
        var: mount_type_changed
