# ansible-playbook -i localhost, playbook.yml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Collect service_facts
      ansible.builtin.service_facts: {}

    - name: Print ansible_facts.services
      debug:
        var: ansible_facts.services
