# ansible-playbook -i localhost, playbook.yml
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    foo:
      listen_addresses: '0.0.0.0'
      password_encryption: scram-sha-256
    tuples:
      - ("key1", "value1")
      - ("key2", "value2")
      
  tasks:
    - name: Print foo
      debug:
        var: foo
    - name: Set fact
      ansible.builtin.set_fact:
        my_dict:
          key: "{{ item.key }}"
          value: "{{ item.value }}"
      loop: "{{ foo | dict2items }}"
    - name: Set fact
      ansible.builtin.set_fact:
        my_dict_from_tuples: "{{ tuples | map('items2dict') | items2dict}}"
    - name: Print my_dict
      debug:
        var: my_dict
    - name: Print my_dict_from_tuples
      debug:
        var: my_dict_from_tuples


