---
- name: Get fingerprints from truststore-based CA certificate file
  community.crypto.x509_certificate_info:
    content: "{{ _cert_content }}"
  register: _ca_info

- name: Store truststore CA fingerprint
  ansible.builtin.set_fact:
    _truststore_fingerprints: "{{ _truststore_fingerprints + [_ca_info.fingerprints] }}"
