# ansible-playbook -i localhost, playbook.yml
# Should result if "true" for "new.crt", and "false" for "old.crt"
---
- name: Test
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cert_and_keystore_check_cert_path: ./old.crt
    cert_and_keystore_check_keystore_path: ./old.p12
    cert_and_keystore_check_keystore_storepass: foobar
    cert_and_keystore_check_truststore_path: ./trust-ca12.jks
    cert_and_keystore_check_ca_certs: ./ca12.crt
    cert_and_keystore_check_truststore_storepass: foobar

  tasks:
    - name: Assume we do not need to regenerate
      set_fact:
        regenerate_keystore_and_truststore: false

    - name: Check keystore
      ansible.builtin.include_tasks: check_keystore.yml
      when: not regenerate_keystore_and_truststore

    - name: Check truststore
      ansible.builtin.include_tasks: check_truststore.yml
      when: not regenerate_keystore_and_truststore

    - name: Print if keystore and/or truststore need to be rebuilt
      ansible.builtin.debug:
        var: regenerate_keystore_and_truststore
